# Generated by Django 3.2.4 on 2021-10-14 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messenger_backend', '0002_message_isread'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='isLastRead',
            field=models.BooleanField(default=False),
        ),
    ]
